version: '3.8'

services:
  # Paper Trading Bot (Test Environment)
  freqtrade-test:
    build: .
    container_name: freqtrade_paper_trading
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./user_data:/freqtrade/user_data
    command: >
      trade
      --config user_data/test_env/config_test.json
      --strategy ScalpingLearner
      --user-data-dir user_data/test_env
      --datadir user_data/test_env/data
    environment:
      - FREQTRADE_DOCKER=1
    networks:
      - freqtrade-network

  # ML Training Bot (Optional - runs separately)
  freqtrade-ml:
    build: .
    container_name: freqtrade_ml_training
    restart: "no"
    profiles:
      - ml
    ports:
      - "8080:8080"
    volumes:
      - ./user_data:/freqtrade/user_data
    command: >
      trade
      --config user_data/ml_env/config_ml.json
      --strategy ScalpingLearner
      --user-data-dir user_data/ml_env
      --datadir user_data/ml_env/data
    environment:
      - FREQTRADE_DOCKER=1
    networks:
      - freqtrade-network

  # Production Bot (Use with extreme caution!)
  freqtrade-production:
    build: .
    container_name: freqtrade_production
    restart: unless-stopped
    profiles:
      - production
    ports:
      - "8082:8082"
    command: >
      trade
      --config user_data/production_env/config_production.json
      --strategy ScalpingLearner
      --user-data-dir user_data/production_env
      --datadir user_data/production_env/data
    volumes:
      - ./user_data:/freqtrade/user_data
    environment:
      - FREQTRADE_DOCKER=1
    networks:
      - freqtrade-network

networks:
  freqtrade-network:
    driver: bridge
